name: Frontend Test and Build

on:
  push:
    branches:
      - main  # Run tests and build on every push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@0.5.7
      with:
        args: --acl public-read --delete
        bucket: ${{ secrets.S3_BUCKET_NAME }}
        region: ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
